name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1    
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
      - name: Restore Packages
        run: nuget restore WebApiV2IntegrationTestsDemo.sln
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE
      - name: Build DotNET
        run: |
         MSBuild.exe WebApiV2IntegrationTestsDemo.sln /p:platform="Any CPU" /p:configuration="Release"
      - name: Run Tests Example01
        run: vstest.console.exe test\Example01.Tests\bin\Release\Example01.Tests.dll
      - name: Run Tests Example02
        run: vstest.console.exe test\Example02.Tests\bin\Release\Example02.Tests.dll
      - name: Run Tests Example03
        run: vstest.console.exe test\Example03.Tests\bin\Release\Example03.Tests.dll
      - name: Run Tests Example04
        run: vstest.console.exe test\Example04.Tests\bin\Release\Example04.Tests.dll